DROP TABLE IF EXISTS user_lists;
CREATE TABLE user_lists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    list_name TEXT NOT NULL,
    list_id TEXT NOT NULL
);