DROP TABLE IF EXISTS user_collections;
CREATE TABLE user_collections (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
    collection_name TEXT NOT NULL,
    bgg_username TEXT NOT NULL
);