DROP TABLE IF EXISTS group_lists;
CREATE TABLE group_lists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_id uuid REFERENCES user_groups(group_id) ON DELETE CASCADE NOT NULL,
    list_id TEXT NOT NULL,
    owner_id uuid REFERENCES users(user_id) ON DELETE CASCADE NOT NULL
);