DROP TABLE IF EXISTS group_collections;
CREATE TABLE group_collections (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_id uuid REFERENCES user_groups(group_id) ON DELETE CASCADE NOT NULL,
    bgg_username TEXT NOT NULL,
    owner_id uuid REFERENCES users(user_id) ON DELETE CASCADE NOT NULL
);