DROP TABLE IF EXISTS group_lists;
CREATE TABLE group_lists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_id uuid NOT NULL,
    FOREIGN KEY (group_id) REFERENCES user_groups(group_id),
    list_id TEXT NOT NULL,
    owner_id uuid NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES users(user_id)
);