DROP TABLE IF EXISTS group_games;
CREATE TABLE group_games (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_id uuid REFERENCES user_groups(group_id) ON DELETE CASCADE NOT NULL,
    owner_id uuid REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
    members TEXT REFERENCES user_groups(members) ON DELETE CASCADE NOT NULL,
    swipes TEXT NOT NULL DEFAULT '{}',
    swipers TEXT NOT NULL DEFAULT '{}',
    matched BOOLEAN NOT NULL DEFAULT false,
    game_name TEXT NOT NULL,
    game_img_url TEXT NOT NULL,
    game_bga_url TEXT NOT NULL
);