DROP TABLE IF EXISTS group_games;
CREATE TABLE group_games (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_id uuid NOT NULL,
    FOREIGN KEY (group_id) REFERENCES user_groups(group_id),
    owner_id uuid NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES users(user_id),
    members TEXT NOT NULL,
    FOREIGN KEY (members) REFERENCES user_groups(members),
    swipes TEXT NOT NULL DEFAULT '{}',
    swipers TEXT NOT NULL DEFAULT '{}',
    matched BOOLEAN DEFAULT false,
    game_name TEXT NOT NULL,
    game_img_url TEXT NOT NULL,
    game_bga_url TEXT NOT NULL
);